---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bc1
patches:
  - target:
      group: cluster.x-k8s.io
      version: v1beta1
      kind: MachineDeployment
      name: .*
    path: machinedeployment-details.yaml
